name: backbone
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/sturdykeep/backbone

environment:
  sdk: ^3.1.0-163.1.beta

# Add regular dependencies here.
dependencies:
  ffi: ^2.0.2
  flutter_rust_bridge: ^1.78.0
  meta: ^1.9.1
  uuid: ^3.0.7
  # path: ^1.8.0

dev_dependencies:
  ffigen: ^8.0.2
  lints: ^2.0.0
  test: ^1.21.0
